addSbtPlugin("com.eed3si9n"      % "sbt-assembly"          % "0.14.6")
addSbtPlugin("com.lucidchart"    % "sbt-scalafmt-coursier" % "1.15")
addSbtPlugin("com.scalapenos"    % "sbt-prompt"            % "1.0.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"   % "1.3.2")
addSbtPlugin("io.get-coursier"   % "sbt-coursier"          % "1.0.0")
